server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pedidos_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

ms-productos:
  url: http://localhost:8081

logging:
  level:
    root: INFO
    com.practica.pedidos: DEBUG
