server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

logging:
  level:
    root: INFO
    com.practica.productos: DEBUG
