server:
  port: 8102

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_pedidos_prd
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

ms-productos:
  url: http://localhost:8101

logging:
  level:
    root: WARN
    com.practica.pedidos: INFO
