server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

ms-productos:
  url: http://localhost:8081

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

logging:
  level:
    root: INFO
    com.practica.pedidos: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/