server:
  port: 8101

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_prd
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

logging:
  level:
    root: WARN
    com.practica.productos: INFO
