server:
  port: 8092

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_qa
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

ms-productos:
  url: http://localhost:8091

logging:
  level:
    root: INFO
    com.practica.pedidos: INFO
