server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

ms-productos:
  url: http://localhost:8081

logging:
  level:
    root: INFO
    com.practica.pedidos: DEBUG
