server:
  port: 8102

spring:
  datasource:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_prd
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

ms-productos:
  url: http://localhost:8101

logging:
  level:
    root: WARN
    com.practica.pedidos: INFO
